apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: student
  labels:
    vol: shared
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 300Mi
  storageClassName: mystore
  hostPath:
    path: /home/student/pvol
    
