apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbox-private-deploy
  labels:
    app: bbox-priv

spec:
  selector:
    matchLabels:
      app: bbox-priv        
  replicas: 1
  strategy:
    type: RollingUpdate
  
  template:
    metadata:
      labels:
        app: bbox-priv        
    spec:
      containers:
        - name: greets-priv
          image: dock01:5001/bbox:oct
          command: 
           - /bin/sh
           - -c
           - |
             echo Test 1 prepare, 30 sec... 
             sleep 30
             echo Test 1 starts, 60 sec 
             dd if=/dev/zero of=/dev/null bs=4096 &
             sleep 60
             kill $!
             echo Test 1 finished.. start pinging
             ping 8.8.8.8 

          resources:  
            limits:
              cpu: 750m
              memory: 30Mi
      imagePullSecrets:
        - name: dock5001        

