apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  namespace: student
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /home/nfsshared
    server: 192.168.56.11
    readOnly: false


