kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: dev-bind 

subjects:
        - kind: ServiceAccount
          name: dev 
          namespace: dev
roleRef:
          kind: ClusterRole
          name: dev
          apiGroup: 'rbac.authorization.k8s.io'         

