kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-unlimited
    namespace: readers

subjects:
        - kind: ServiceAccount
          name: readers-unlimited
          namespace: readers

roleRef:
          kind: ClusterRole
          name: readers-unlimited
          apiGroup: 'rbac.authorization.k8s.io'         

