kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-student-bind
    namespace: student

subjects:
        - kind: ServiceAccount
          name: student
          namespace: student

roleRef:
          kind: ClusterRole
          name: readers-limited 
          apiGroup: 'rbac.authorization.k8s.io'         

