kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-limited-bind
    namespace: student

subjects:
        - kind: ServiceAccount
          name: readers
          namespace: student
roleRef:
          kind: ClusterRole
          name: readers-limited1
          apiGroup: 'rbac.authorization.k8s.io'         

