kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-all-student
    namespace: student 

rules:

  - apiGroups: ["*"]
    #    resources: ["pods","pods/log","nodes","services","jobs","cronjobs","deployments"]
    resources: ["*"]
    verbs: ["get","list","watch"] 

  - apiGroups: ["batch"]
    resources: ["jobs","cronjobs"]
    verbs: ["get","list","watch"]

