kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-all
    namespace: student 
    #  labels:

rules:
  - apiGroups: [""]
    #    resources: ["pods","pods/log","nodes","services","jobs","cronjobs","deployments"]
    resources: ["*"]
    verbs: ["get","list","watch"] 

  - apiGroups: ["apps"]
    #    resources: ["pods","pods/log","nodes","services","jobs","cronjobs","deployments"]
    resources: ["*"]
    verbs: ["get","list","watch"] 

  - apiGroups: ["batch"]
    resources: ["jobs","cronjobs"]
    verbs: ["get","list","watch"]
    
  - apiGroups: ["extensions"]
    #    resources: ["pods","pods/log","nodes","services","jobs","cronjobs","deployments"]
    resources: ["*"]
    verbs: ["get","list","watch"] 

    #  - apiGroups: ["batch"]
    #    resources: ["pods","pods/log","nodes","services","jobs","cronjobs","deployments"]
    #resources: ["*"]
    #verbs: ["get","list","watch"] 




