kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-all-student-bind
    namespace: student

subjects:
        - kind: ServiceAccount
          name: helpdesk 
          namespace: student

roleRef:
          kind: Role
          name: readers-all-student
          apiGroup: 'rbac.authorization.k8s.io'         

