apiVersion: v1
kind: Pod
metadata:
  name: pod-conf-map
  namespace: student

spec:
  imagePullSecrets:
    - name: dock5001
  containers:
    - name: ctr-conf-map
      image: dock01:5001/bbox:nov
      command: 
        - /bin/sh 
        - -c
        - |
          echo started!!
          sleep 60
          env
          sleep 30
          cat /etc/resolv.conf
          sleep 10
          ping 1.1.1.1
             
      envFrom:
      - configMapRef:
          name: greets
      - configMapRef:
          name: greets2
          
