apiVersion: v1
kind: Pod
metadata:
  name: pod-conf-map
  namespace: student

spec:
  containers:
    - name: ctr-conf-map
      image: busybox
      command: 
        - /bin/sh 
        - -c
        - |
          echo started!!
          sleep 60
          env
          sleep 30
          cat /etc/resolv.conf
          sleep 10
          ping 1.1.1.1

              
      env:
        - name: Hello
          valueFrom:
            configMapKeyRef:
              name: greets
              key: greets
