#!/bin/bash

tput setaf 2 && echo installing k8s master node... && tput setaf 7

systemctl stop firewalld && systemctl disable firewalld  
swapoff -a  
sudo sed -E -i 's/^\/(.*swap.*)/#\/\1/' /etc/fstab

cat <<EOT > /etc/modules-load.d/k8s.conf
br_netfilter
overlay
EOT

modprobe br_netfilter && modprobe overlay

#iptables -I INPUT 1 -p tcp --match multiport --dports 6443,2379:2380,10250:10252 -j ACCEPT

#systemctl install -y iptables iptables-services
#systemctl install -y iptables-legacy
#update-alternatives --set iptables /usr/sbin/iptables-legacy
#systemctl enable iptables && systemctl start iptables

cat <<EOT > /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward=1
EOT

sysctl --system

cat <<'EOF' > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
enabled=0
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

#um makecache && yum install -y kubeadm-1.25.7-0 kubelet-1.25.7-0 kubectl-1.25.7-0 cri-tools
yum makecache && yum install --enablerepo=kubernetes -y kubelet kubeadm kubectl cri-tools

dnf install -y python3-dnf-plugin-versionlock
dnf versionlock add kubelet kubeadm kubectl

service docker restart

# this 2 lines remove the bug "Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
# for k8s version > 1.19.*, containerd.io > 1.3.*, os = ubuntu 20.04
rm /etc/containerd/config.toml
systemctl restart containerd

#rand=`shuf -er -n10 {A..Z} {a..z} {0..9} '!' @ | tr -d '\n'`
#cp /etc/sysconfig/iptables /var/"iptables-$rand"
#iptables-save > /etc/sysconfig/iptables

tput setaf 2 && echo pulling k8s images... && tput setaf 7

kubeadm config images pull
tput setaf 2 && echo "init kube  ..  pod-network: 10.244.0.0/16" && tput setaf 7
kubeadm init --pod-network-cidr=10.244.0.0/16 #--apiserver-advertise-address=172.17.17.131

systemctl enable containerd
systemctl enable kubelet && systemctl start kubelet

tput setaf 2 && echo "start set up vars, alias and kubectl autocompleteion rules.." && tput setaf 7

export KUBECONFIG=/etc/kubernetes/admin.conf

dnf install -y bash-completion

source /usr/share/bash-completion/bash_completion

cat <<EOT >> /etc/modules-load.d/k8s.conf
source /usr/share/bash-completion/bash_completion
EOT

echo 'source <(kubectl completion bash)' >> /etc/bash.bashrc
echo 'alias k=kubectl' >> /etc/bash.bashrc
echo 'complete -F __start_kubectl k' >> /etc/bash.bashrc

tput setaf 2 && echo "Done. Next steps: 1. Install overlay driver on master (node) - here. 2. Add worker nodes" && tput setaf 7


#kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml




