apiVersion: v1

kind: Pod
metadata:
  name: bbox-hiload-pod
  namespace: student

spec:
  nodeSelector:
    mem: high

  containers:
    - image: busybox
      name: bbox-hl
      command: 
        - bin/sh
        - -c
        - dd if=/dev/random of=/dev/null
      
      resources:
        limits:
          cpu: "150m"
          memory: 30M

