apiVersion: v1

kind: Pod
metadata:
  name: bbox-pod
  namespace: student

spec:
#  nodeSelector:
#    mem: high

  containers:
    - image: busybox
      name: bbox-cont1
      command: 
        - bin/sh
        - -c
        - ping 1.1.1.1

    - image: busybox
      name: bbox-cont2
      command: 
        - bin/sh
        - -c
        - ping ya.ru

